In [21]:
import numpy as np
import pandas as pd
class Perceptron():
  def __init__(self, eta=0.01, n_iter=10):
    self.weights=np.random.randn(2)*1e-4
    self.bias=np.random.randn(1)
    print(f"Weights: {self.weights}\n Bias: {self.bias}")
    self.eta = eta
    self.n_iter = n_iter
  def activationfunction(self,X):
    z=np.dot(X,self.weights)+self.bias
    return np.where(z>0,1,0)
  def fit(self, X, y):
    self.X=X
    self.y=y
    for i in range(self.n_iter):
      print(f"{i}th epoch")
      y_hat=self.activationfunction(self.X)
      print(f"predicted value: \n{y_hat}")
      error=self.y-y_hat
      print(f"error: \n{error}")
      if(error==0).all(): # Corrected line: Added .all() to resolve ValueError
        print("Training completed")
        break
      self.weights=self.weights+self.eta*np.dot(self.X.T,error)
      self.bias=self.bias+self.eta*np.sum(error)
      print(f"updated weights: \n{self.weights}")
      print("#############\n")
  def predict(self,X):
    return self.activationfunction(X)

In [24]:
data = {"x1": [0,0,1,1], "x2": [0,1,0,1], "y": [0,1,1,1]}

AND = pd.DataFrame(data)
X = AND.drop("y", axis=1)
y = AND['y']
y.to_frame()
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [25]:
model = Perceptron(eta = 0.5, n_iter=10)
model.fit(X,y)

Weights: [-2.42660334e-05  4.84980838e-05]
 Bias: [0.67329704]
0th epoch
predicted value: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[-2.42660334e-05  4.84980838e-05]
#############

1th epoch
predicted value: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[-2.42660334e-05  4.84980838e-05]
#############

2th epoch
predicted value: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    1
Name: y, dtype: int64
updated weights: 
[0.99997573 1.0000485 ]
#############

3th epoch
predicted value: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[0.99997573 1.0000485 ]
#############

4th epoch
predicted value: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[0.99997573 1.0000485 ]
#############

5th epoch
predicted value: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[0.99997573 1.0000485 ]
#############


In [26]:
model.predict(X)

array([0, 1, 1, 1])